import express from "express";
import { protectedRout } from "../Middlewares/Authentication.js";
import { createTransaction, getAllTransactions, getMonthlySummary, getOneTransaction, updateTransaction } from "../Controllers/Transactions.js";
const router = express.Router();
router.get("/all", protectedRout, getAllTransactions);
router.get("/one:id", protectedRout, getOneTransaction);
router.get("/monthly-summary", protectedRout, getMonthlySummary);
router.post("/create", protectedRout, createTransaction);
router.put("/update:id", protectedRout, updateTransaction);
export default router;